from __future__ import annotations

import json
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from matrix_codex.health_scanner import HealthScanner, ScannerConfig
from matrix_codex.inventory.org_discovery import GitHubOrgDiscovery
from matrix_codex.main import check_single_repo, plan_maintenance, run_daily, run_maintenance, scan_health
from matrix_codex.models import MaintenanceTask
from matrix_codex.reporting.status_builder import build_status
from matrix_codex.settings import get_settings
from matrix_codex.logging import configure_logging
from matrix_codex.site.generator import generate_site
from matrix_codex.storage.models import StorageDB
from matrix_codex.task_engine import create_tasks

app = typer.Typer(add_completion=False, help="matrix-codex CLI")
console = Console()


@app.callback()
def _callback() -> None:
    settings = get_settings()
    configure_logging(settings.log_level)


@app.command("discover")
def discover() -> None:
    settings = get_settings()
    repos = GitHubOrgDiscovery(settings).list_repositories()
    table = Table(title="Repositories")
    table.add_column("Name")
    table.add_column("Default branch")
    for repo in repos:
        table.add_row(repo.full_name, repo.default_branch)
    console.print(table)


@app.command("scan-health")
def scan_health_cmd() -> None:
    settings = get_settings()
    issues = scan_health(settings)
    console.print_json(data={"issues": [issue.model_dump(mode="json") for issue in issues]})


@app.command("plan-maintenance")
def plan_maintenance_cmd() -> None:
    settings = get_settings()
    scanner = HealthScanner(ScannerConfig(repositories_file=Path("config/repositories.yml")))
    issues = scanner.scan()
    tasks = plan_maintenance(settings, issues)
    console.print_json(data={"tasks": [task.model_dump(mode="json") for task in tasks]})


@app.command("run-maintenance")
def run_maintenance_cmd(task_json: str = typer.Option("", help="Optional single task payload as JSON.")) -> None:
    settings = get_settings()
    if task_json:
        task = MaintenanceTask.model_validate(json.loads(task_json))
        reports = run_maintenance(settings, [task])
    else:
        issues = scan_health(settings)
        tasks = create_tasks(issues, Path("config/tasks.yml"))
        reports = run_maintenance(settings, tasks)
    console.print_json(data={"reports": [r.model_dump(mode="json") for r in reports]})


@app.command("report-status")
def report_status_cmd() -> None:
    settings = get_settings()
    db = StorageDB(settings.state_dir / "maintainer_records.json")
    status = build_status(settings)
    status["maintainer"] = {
        "runs": len(db.list("runs")),
        "tasks": len(db.list("tasks")),
        "events": len(db.list("events")),
    }
    (settings.state_dir / "latest_status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    generate_site(settings)
    console.print("Status updated")


@app.command("run-daily")
def run_daily_cmd() -> None:
    settings = get_settings()
    reports = run_daily(settings)
    console.print(f"Processed {len(reports)} maintenance tasks")


@app.command("publish-site")
def publish_site() -> None:
    settings = get_settings()
    generate_site(settings)
    console.print("Status site generated")


@app.command("check-repo")
def check_repo(repo_name: str) -> None:
    settings = get_settings()
    repo = next((r for r in GitHubOrgDiscovery(settings).list_repositories() if r.name == repo_name or r.full_name == repo_name), None)
    if repo is None:
        raise typer.Exit(f"Repository not found: {repo_name}")
    report = check_single_repo(repo, settings)
    console.print_json(data=report.model_dump(mode="json"))


@app.command("check-make")
def check_make(
    targets: list[str] = typer.Argument(  # noqa: B008
        None, help="Make targets to run, in order. Default: install test."
    ),
    cwd: Path = typer.Option(  # noqa: B008
        Path.cwd(),
        "--cwd",
        help="Working directory of the target repository (default: cwd).",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        help="Optional path to write the structured JSON report to.",
    ),
    repo: str | None = typer.Option(
        None,
        "--repo",
        help="owner/repo identifier to embed in the report (default: $GITHUB_REPOSITORY).",
    ),
) -> None:
    """Run `make <target>` in order; emit a structured JSON report.

    This is the runtime invoked by the `matrix-maintenance.yml` workflow
    generated by SelfRepair's wizard. Exit code 0 when every target
    succeeds; non-zero on first failure.
    """
    import os
    import shlex
    import subprocess
    import datetime as _dt

    if not targets:
        targets = ["install", "test"]

    repo_id = repo or os.environ.get("GITHUB_REPOSITORY") or "(unknown)"
    started_at = _dt.datetime.now(_dt.timezone.utc).isoformat()
    steps_report: list[dict] = []
    overall_status = "ok"
    failed_step: str | None = None

    for target in targets:
        cmd = ["make", target]
        console.log(f"[matrix-maintainer] running: {shlex.join(cmd)} (cwd={cwd})")
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
        )
        steps_report.append(
            {
                "target": target,
                "exit_code": proc.returncode,
                "stdout_tail": proc.stdout[-2000:],
                "stderr_tail": proc.stderr[-2000:],
            }
        )
        if proc.returncode != 0:
            overall_status = "failed"
            failed_step = target
            break

    report = {
        "schema_version": "0.1",
        "source": "matrix-maintainer.cli",
        "type": "maintenance.check.completed",
        "repo": repo_id,
        "started_at": started_at,
        "finished_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "targets": targets,
        "status": overall_status,
        "failed_step": failed_step,
        "steps": steps_report,
    }
    text = json.dumps(report, indent=2)
    if output:
        output.write_text(text + "\n", encoding="utf-8")
    console.print(text)
    raise typer.Exit(code=0 if overall_status == "ok" else 1)


if __name__ == "__main__":
    app()
